bbs/urls.py
from django.urls import path

from bbs.views import *
urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('category/<str:code>', CategoryView.as_view(), name='category'),
	path('detail/<int:pk>.html', ArticleView.as_view(), name='detail'),
	path('detail/<int:good>/', ArticleView.as_view(), name='detail_good'),
	path('leader/', LeaderView.as_view(), name='leader'),
]

generic/urls.py
from django.urls import path

from generic.views import *

urlpatterns = [
	path('login/', SoaziLoginView.as_view(), name='login'),
	path('register/', SoaziRegisterView.as_view(), name='register'),
	path('logout/', SoaziLogoutView.as_view(), name='logout'),
	path('private/<int:pk>/', SoaziManageView.as_view(), name='private'),
]

soazi/urls.py
from django.contrib import admin
from django.urls import path, include

from bbs.views import IndexView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view()),
    path('base/', include(('generic.urls', 'generic'), namespace='generic')),
    path('bbs/', include(('bbs.urls', 'bbs'), namespace='bbs')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

generic/models.py
from django.db import models
from django.contrib.auth.models import (
	AbstractBaseUser, BaseUserManager
)

# Create your models here.

class SoaziUserManager(BaseUserManager):
	
	def create_user(self, email, username, password=None):
		if not username:
			raise ValueError('请输入正确的用户名!')
		user = self.model(
			email=self.normalize_email(email),
			username=username
		)
		user.set_password(password)
		user.save(using=self._db)
		return user
	
	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=email,
			username=username,
			password=password
		)
		user.is_admin = True
		user.save(using=self._db)
		return user


class SoaziBaseUser(AbstractBaseUser):
	email = models.EmailField(verbose_name='用户邮箱', max_length=128, unique=True)
	username = models.CharField(verbose_name='用户名', max_length=12)
	
	is_active = models.BooleanField(default=True)
	is_admin = models.BooleanField(default=False)
	
	created = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
	updated = models.DateTimeField(verbose_name='更新时间', auto_now=True)
	
	objects = SoaziUserManager()
	
	EMAIL_FIELD = 'email'
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = 'username',
	
	class Meta:
		unique_together = 'email', 'username'
		db_table = 'user'
		verbose_name = verbose_name_plural = '用户列表'
	
	def __str__(self):
		return self.username
	
	def has_perm(self, perm, obj=None):
		return True
	
	def has_module_perms(self, app_label):
		return True
	
	@property
	def is_staff(self):
		return self.is_admin

generic/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from generic.models import *

class SoaziUserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='密码', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(label='重复密码', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	
	class Meta:
		model = SoaziBaseUser
		fields = 'email', 'username'
		widgets = {
			'email': forms.EmailInput(attrs={'class': 'form-control'}),
			'username': forms.TextInput(attrs={'class': 'form-control'}),
		}
	
	def clean_passwod2(self):
		password1 = self.cleaned_data.get('password1', None)
		password2 = self.cleaned_data.get('password2', None)
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError('密码错误!')
		return password2
	
	def save(self, commit=True):
		user = super(SoaziUserCreationForm, self).save(commit=True)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user


class SoaziUserChangeForm(forms.ModelForm):
	password = ReadOnlyPasswordHashField()
	
	class Meta:
		model = SoaziBaseUser
		fields = 'email', 'username', 'is_active', 'is_admin'
	
	def clean_password(self):
		return self.initial['password']

generic/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin


from generic.models import *
from generic.forms import *
from bbs.models import ArticleList as BBSArticleList
# Create your views here.

class SoaziLoginView(LoginView):
	template_name = 'generic/login.html'
	redirect_field_name = '/'
	
	def get_form(self, form_class=None):
		kwargs = super(SoaziLoginView, self).get_form(form_class)
		kwargs.fields['username'].widget.attrs = {"class": "form-control"}
		kwargs.fields['password'].widget.attrs = {"class": "form-control"}
		return kwargs

class SoaziRegisterView(CreateView):
	template_name = 'generic/register.html'
	form_class = SoaziUserCreationForm
	success_url = '/'


class SoaziLogoutView(LogoutView):
	template_name = 'bbs/index.html'
	next_page = '/'

class SoaziManageView(DetailView, LoginRequiredMixin):
	template_name = 'generic/private.html'
	model = SoaziBaseUser
	context_object_name = 'userinfo'
	
	def get_context_data(self, **kwargs):
		kwargs['bbs_articles'] = BBSArticleList.objects.filter(author__id=self.kwargs['pk']).values('id', 'topic',
		                                                                                         'visits', 'likes',
		                                                                                         'created')
		return super(SoaziManageView, self).get_context_data(**kwargs)

templates/generic/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/extra/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'custom/bbs.css' %}">
    {% block style %}{% endblock style %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Brand</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'bbs:index' %}">首页 <span class="sr-only">(current)</span></a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">{{ request.user }}</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'generic:private' user.id %}">用户中心</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            {% if user.is_admin %}
                            <li><a href="/admin/">后台管理中心</a></li>
                            <li role="separator" class="divider"></li>
                            {% endif %}
                            <li><a href="{% url 'generic:logout' %}">注销</a></li>
                        </ul>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
{% block content %}{% endblock content %}
<script src="{% static 'bootstrap/extra/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'wangeditor/wangEditor.min.js' %}"></script>
{% block script %}{% endblock script %}
</body>
</html>

templates/generic/login.html
{% extends 'generic/base.html' %} {% load static %}
{% block style %}
    <style>
        .auth{
            margin-top:15%;
            box-shadow:0 0 1px 1px #ccc;
            border-radius:7px;
            padding-top:40px;
        }
        .auth table{
            border-collapse: separate;
            border-spacing: 15px;
        }
        .auth table tr:not(:last-child){
            height:40px;
            line-height: 40px;
        }
    </style>
{% endblock style %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="auth" id="login">
                    <form action="{% url 'generic:login' %}" method="post">
                        {% csrf_token %}
                        <table align="center" width="360px">
                            <tr>
                                <td colspan="2" align="left" style="border-bottom:1px solid #ccc">
                                    <h3>用户登陆</h3>
                                </td>
                            </tr>
                            {{ form.as_table }}
                            <tr>
                                <td colspan="2" align="center">
                                    <button class="btn btn-info" type="submit">
                                        登陆
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" align="right">
                                    <a href="{% url 'generic:register' %}">没有账号?注册一个!</a>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/generic/private.html
{% extends 'bbs/index.html' %} {% load static %} {% load bbs_extras %}
{% block style %}
    <style>
    #userinfo-left img{
        height:120px;
        width:120px;
        margin-top:20px;
        margin-bottom:15px;
    }
    #userinfo-left>div>span{
        font-size:16px;
        font-weight:600;
        color:#333;
        margin:7px auto;
    }
    #userinfo-right table{
        font-size:16px;
        margin:20px auto;
    }
    #auth-nav{
        border-top:1px solid rgba(0,0,0,.08);
        padding:0;
        border-bottom:1px solid rgba(0,0,0,.08);
    }
    #auth-nav>ul{
        margin:0;
    }
    #auth-nav>ul>li{
        text-align:center;
        position: relative;
    }
    #auth-nav>ul>li>a{
        height:50px;
        line-height: 50px;
        width:140px;
        color:#333;
        font-weight:600;
        font-family: 'Microsoft YaHei UI Light';
        display:block;
        text-decoration: none;
    }
    #auth-nav>ul>li>a:hover{
        box-shadow:0 0 1px 1px rgba(0,0,0,.05);
    }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default" style="border-radius:0;">
                    <div class="panel-heading" style="background-color:transparent">
                        个人信息
                    </div>
                    <div class="panel-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-6" id="userinfo-left" style="box-shadow:1px 0 0 #ccc">
                                    <img src="{% static 'custom/topic.jpg' %}" alt="..." class="img-circle center-block">
                                    <div class="text-center">
                                        <span class="center-block">{{ user.username }}</span>
                                        <span class="center-block">{{ user.email }}</span>
                                    </div>
                                </div>
                                <div class="col-md-6" id="userinfo-right">
                                    <table>
                                        <tr>
                                            <td width="35%">创建于:</td>
                                            <td>{{ user.created }}</td>
                                        </tr>
                                        <tr>
                                            <td>最后修改:</td>
                                            <td>{{ user.updated }}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body" id="auth-nav">
                        <ul class="list-inline">
                            <li class="active">
                                <a href="#bbs">论坛文章</a>
                            </li>
                            <li>
                                <a href="#blog">博客文章</a>
                            </li>
                        </ul>
                    </div>
                    <div class="panel-body tab-content">
                        <div id="bbs" class="tab-pane fade active in">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th width="40%">标题</th>
                                        <th>浏览量</th>
                                        <th>点赞数</th>
                                        <th>发布时间</th>
                                        <th>回复数</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in bbs_articles %}
                                    <tr>
                                        <td>{{ i.topic }}</td>
                                        <td>{{ i.visits }}</td>
                                        <td>{{ i.likes }}</td>
                                        <td>{{ i.created }}</td>
                                        <td>{{ i.id|reply_num }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div id="blog" class="tab-pane fade">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th width="40%">标题</th>
                                        <th>浏览量</th>
                                        <th>点赞数</th>
                                        <th>发布时间</th>
                                        <th>回复数</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in blog_articles %}
                                    <tr>
                                        <td>{{ i.topic }}</td>
                                        <td>{{ i.visits }}</td>
                                        <td>{{ i.likes }}</td>
                                        <td>{{ i.created }}</td>
                                        <td>{{ i.id }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
    <script>
    $('#auth-nav>ul>li>a').click(function(){
        $(this).tab('show');
    })
    </script>
{% endblock script %}

templates/generic/register.html
{% extends 'generic/base.html' %} {% load static %}
{% block style %}
    <style>
        .auth{
            margin-top:15%;
            box-shadow:0 0 1px 1px #ccc;
            border-radius:7px;
            padding-top:40px;
        }
        .auth table{
            border-collapse: separate;
            border-spacing: 15px;
        }
        .auth table tr:not(:last-child){
            height:40px;
            line-height: 40px;
        }
    </style>
{% endblock style %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="auth" id="login">
                    <form action="{% url 'generic:register' %}" method="post">
                        {% csrf_token %}
                        <table align="center" width="360px">
                            <tr>
                                <td colspan="2" align="left" style="border-bottom:1px solid #ccc">
                                    <h3>用户注册</h3>
                                </td>
                            </tr>
                            {{ form.as_table }}
                            <tr>
                                <td colspan="2" align="center">
                                    <button class="btn btn-info" type="submit">
                                        登陆
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" align="right">
                                    <a href="{% url 'generic:login' %}">已有账号?返回登录!</a>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}