bbs/urls.py
from django.urls import path

from bbs.views import *
urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('category/<str:code>', CategoryView.as_view(), name='category'),
	path('detail/<int:pk>.html', ArticleView.as_view(), name='detail'),
	path('detail/<int:good>/', ArticleView.as_view(), name='detail_good'),
	path('leader/', LeaderView.as_view(), name='leader'),
]

generic/urls.py
from django.urls import path

from generic.views import *

urlpatterns = [
	path('login/', SoaziLoginView.as_view(), name='login'),
	path('register/', SoaziRegisterView.as_view(), name='register'),
	path('logout/', SoaziLogoutView.as_view(), name='logout'),
	path('private/<int:pk>/', SoaziManageView.as_view(), name='private'),
]

soazi/urls.py
from django.contrib import admin
from django.urls import path, include

from bbs.views import IndexView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view()),
    path('base/', include(('generic.urls', 'generic'), namespace='generic')),
    path('bbs/', include(('bbs.urls', 'bbs'), namespace='bbs')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

bbs/models.py
from django.db import models

from generic.models import SoaziBaseUser
# Create your models here.

class CodeList(models.Model):
	
	code = models.CharField(verbose_name='语言', max_length=12)
	
	created = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
	
	class Meta:
		db_table = 'bbs_code'
		verbose_name = verbose_name_plural = '语言分类'
	
	def __str__(self):
		return self.code


class ArticleList(models.Model):
	topic = models.CharField(verbose_name='标题', max_length=128)
	description = models.CharField(verbose_name='描述', max_length=256)
	content = models.TextField(verbose_name='内容')
	author = models.ForeignKey(SoaziBaseUser, verbose_name='作者', on_delete=models.CASCADE)
	code = models.ForeignKey(CodeList, verbose_name='分类', on_delete=models.CASCADE)
	
	visits = models.PositiveIntegerField(verbose_name='浏览数量', default=0)
	likes = models.PositiveIntegerField(verbose_name='点赞数量', default=0)
	
	created = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
	updated = models.DateTimeField(verbose_name='修改时间', auto_now=True)
	
	class Meta:
		db_table = 'bbs_article'
		verbose_name = verbose_name_plural = '文章列表'
	
	def __str__(self):
		return self.topic


class ReplyList(models.Model):
	topic = models.ForeignKey(ArticleList, verbose_name='标题', on_delete=models.CASCADE)
	content = models.CharField(verbose_name='内容', max_length=512)
	author = models.ForeignKey(SoaziBaseUser, verbose_name='作者', on_delete=models.CASCADE)
	likes = models.PositiveIntegerField(verbose_name='点赞数量')
	
	created = models.DateTimeField(verbose_name='回复时间', auto_now_add=True)
	
	class Meta:
		db_table = 'bbs_reply'
		verbose_name = verbose_name_plural = '回复列表'
	
	def __str__(self):
		return self.topic.topic


class LabelList(models.Model):
	topic = models.ForeignKey(ArticleList, verbose_name='标题', on_delete=models.CASCADE)
	label = models.CharField(verbose_name='标签', max_length=24)
	
	created = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
	
	class Meta:
		db_table = 'bbs_label'
		verbose_name = verbose_name_plural = '标签列表'
	
	def __str__(self):
		return self.topic.topic


class PushLog(models.Model):
	username = models.ForeignKey(SoaziBaseUser, verbose_name='用户名', on_delete=models.CASCADE)
	topic = models.ForeignKey(ArticleList, verbose_name='文章', on_delete=models.CASCADE)
	
	class Meta:
		db_table = 'pushlog'
		verbose_name = verbose_name_plural = '操作记录'
	
	def __str__(self):
		return self.username.username

bbs/forms.py
from django import forms

from bbs.models import *

class NewArticleForm(forms.ModelForm):
	
	class Meta:
		style = {'class': 'form-control'}
		model = ArticleList
		fields = 'topic', 'description', 'code', 'content'
		widgets = {
			'topic': forms.TextInput(attrs=style),
			'description': forms.TextInput(attrs=style),
			'code': forms.TextInput(attrs=style),
			'content': forms.Textarea(attrs={'class': 'sr-only'})
		}
		
	def __init__(self, *args, **kwargs):
		super(NewArticleForm, self).__init__(*args, **kwargs)
		self.fields['code'].empty_label = None
	
		

class ReplyForm(forms.ModelForm):
	
	class Meta:
		style = {'class': 'form-control'}
		model = ReplyList
		fields = 'content',

bbs/views.py
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.db.models import F
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from bbs.models import *
from bbs.forms import *

import json
# Create your views here.

class IndexView(ListView):
	template_name = 'bbs/index.html'
	model = ArticleList
	context_object_name = 'articles'
	
	def get_context_data(self, **kwargs):
		kwargs['codes'] = CodeList.objects.values('code')
		kwargs['newarticle'] = NewArticleForm
		return super(IndexView, self).get_context_data(**kwargs)
	
	def http_method_not_allowed(self, request, *args, **kwargs):
		if request.method == 'POST':
			topic = request.POST['topic']
			description = request.POST['description']
			content = request.POST['content']
			code = request.POST['code']
			author = request.user
			iz = CodeList.objects.get_or_create(code=code)
			article = self.model(topic=topic, description=description, content=content, author=author, code=iz[0])
			article.save()
		return HttpResponseRedirect('/')

class CategoryView(ListView):
	template_name = 'bbs/index.html'
	model = ArticleList
	context_object_name = 'articles'
	
	def get_context_data(self, **kwargs):
		kwargs['codes'] = CodeList.objects.values('code')
		kwargs['newarticle'] = NewArticleForm
		return super(CategoryView, self).get_context_data(**kwargs)
	
	def get_queryset(self):
		code = self.kwargs.get('code', None)
		return super(CategoryView, self).get_queryset().filter(code__code=code)
	
class ArticleView(DetailView):
	template_name = 'bbs/detail.html'
	model = ArticleList
	context_object_name = 'article'

	def get_context_data(self, **kwargs):
		kwargs['reply'] = ReplyList.objects.filter(topic=self.kwargs.get('pk')).values('content', 'author', 'created')
		kwargs['replyform'] = ReplyForm
		return super(ArticleView, self).get_context_data(**kwargs)

	def get_object(self, queryset=None):
		kwargs = super(ArticleView, self).get_object(queryset)
		kwargs.visits +=1
		kwargs.save()
		return kwargs

	def http_method_not_allowed(self, request, *args, **kwargs):
		id = self.kwargs.get('good', None)
		if id:
			article = ArticleList.objects.get(id=id)
			if article:
				ck = PushLog.objects.get_or_create(topic=article, username=request.user)
				if ck[1]:
					article.likes += 1
					article.save()
					num = {'over': article.likes}
				else:
					num = {'over': '请勿重复操作!'}
			else:
				num = {'over': '系统发生错误!'}
		return HttpResponse(json.dumps(num), content_type='application/json')

class LeaderView(TemplateView):
	template_name = 'bbs/leader.html'
	
	def get_context_data(self, **kwargs):
		kwargs['hot_leader'] = ArticleList.objects.order_by('-visits')[:10].values('id', 'topic', 'visits')
		kwargs['like_leader'] = ArticleList.objects.order_by('-likes')[:10].values('id', 'topic', 'likes')
		return super(LeaderView, self).get_context_data(**kwargs)

templates/bbs/detail.html
{% extends 'generic/base.html' %} {% load staticfiles %} {% load bbs_extras %}
{% block style %}
    <link rel="stylesheet" href="{% static 'bootstrap/extra/toastr.min.css' %}">
{% endblock style %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-default bbs-detail-main">
                    <div class="panel-heading">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>{{ article.topic }}</h4>
                                </div>
                            </div>
                            <div class="row">
                                <ul class="list-unstyled list-inline col-md-12" style="margin-bottom:0;">
                                    <li>
                                        <a href="#">{{ article.author }}</a>
                                    </li>
                                    <li>
                                        <i class="icon">&#xe65f;</i> {{ article.created }}
                                    </li>
                                    <li>
                                        <i class="icon">&#xe7f4;</i> {{ article.visits }}人浏览
                                    </li>
                                    <li>
                                        {{ article.likes }}
                                    </li>
                                    <li style="float:right;user-select:none;">
                                        <span style="border:1px solid #ccc;padding:3px 7px;color:#bbb;">{{ article.code }}</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body" style="padding-bottom:0;">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    {{ article.content }}
                                </div>
                            </div>
                            <div class="row" style="margin-top:30px;">
                                <div class="col-md-12">
                                    <ul class="list-unstyled list-inline" style="margin-bottom:0;">
                                        <li>
                                            <button id="good" class="btn btn-link"><i class="icon">&#xe7e1;</i> 点赞</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <h3>回复</h3>
                                </div>
                            </div>
                            <div class="row" id="reply">
                                <form class="col-md-12">
                                    <div class="form-group sr-only">
                                        {{ replyform.content }}
                                    </div>
                                    <div class="form-group" id="reply-content"></div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-default btn-block">提交</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer" style="border-top:none;padding-bottom:25px;padding-top:0;">
                        <div class="container-fluid">
                            <div class="row" style="border-bottom:1px solid #ddd;">
                                <div class="col-md-4">
                                    <h3>评论区</h3>
                                </div>
                            </div>
                            {% for row in reply %}
                            <div class="row reply">
                                <div class="col-md-2">
                                    <div class="reply-author-img">
                                        <img src="{% static 'custom/topic.jpg' %}" class="img-circle" width="100%" height="100%" alt="">
                                    </div>
                                    <div class="reply- text-center">
                                        <span class="center-block">{{ row.author }}</span>
                                        <a href="#" class="center-block text-muted" style="margin-top:5px;text-decoration: none;"><i class="icon" style="font-size:16px;">&#xe7e1;</i></a>
                                    </div>
                                </div>
                                <div class="col-md-8" style="height:100%;">
                                    <div style="height:80%">
                                        {{ row.content }}
                                    </div>
                                    <ul class="list-unstyled list-inline" style="margin:0;">
                                        <li>
                                            <i class="icon">&#xe65f;</i> {{ row.created }}
                                        </li>
                                        <li>
                                            <a href="#"><i class="icon">&#xe7e0;</i> 回复</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
    <script src="{% static 'bootstrap/extra/toastr.min.js' %}"></script>
    <script>
        var E = window.wangEditor;
        var editor = new E('#reply-content');
        editor.customConfig.onchange = function(html){
            $('#id_content').val(html);
        };
        editor.create();
        $('#id_content').val(editor.txt.html());
        toastr.options = {
            'positionClass': 'toast-top-center',
            'timeOut': 300
        }
        $('#good').click(function(){
            $.ajax({
                url: "{% url 'bbs:detail_good' article.id %}",
                type: 'post',
                data:{
                    csrfmiddlewaretoken:'{{ csrf_token }}'
                },
                success: function(value){
                    if (typeof(value.over)=='Number'){
                        toastr.info('<赞>+1, 共'+value.over);
                    }else{
                        toastr.error(value.over);
                    }
                }
            })
        })
    </script>
{% endblock script %}

templates/bbs/index.html
{% extends 'generic/base.html' %}{% load static %}{% load bbs_extras %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5 col-md-offset-2 col-sm-12 col-xs-12">
                <div class="panel panel-default bbs-main">
                    <div class="panel-heading bbs-heading">
                        {% if codes %}
                            <div class="container-fluid">
                                <div class="row">
                                    {% for code in codes %}
                                        <div class="col-sm-2 col-xs-2">
                                            <a href="{% url 'bbs:category' code.code %}" class="button button-small">{{ code.code }}</a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% else %}
                            <h5 style="margin:0 3%;font-weight:400;font-size:16px;user-select:none;">文章列表</h5>
                        {% endif %}
                    </div>
                    <div class="panel-body bbs-body">
                        <div class="container-fluid">
                            {% for article in articles %}
                                <a class="row center-block" href="{% url 'bbs:detail' article.pk %}" id="article-footer">
                                    <div class="col-sm-8 col-xs-8" id="article-footer-left">
                                        <h4>{{ article.topic }}</h4>
                                        <div class="description">
                                            {{ article.description }}
                                        </div>
                                        <ul class="list-inline list-style">
                                            <li>
                                                <label class="code">{{ article.code }}</label>
                                            </li>
                                            <li>
                                                <span class="author">{{ article.author }}</span>
                                            </li>
                                            <li>
                                                <span class="created"><i class="icon">&#xe74a;</i> {{ article.created|date:'Y-m-d' }}</span>
                                            </li>
                                            <li>
                                                <span class="visits"><i class="icon">&#xe7f4;</i> {{ article.visits }}人浏览</span>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-4 col-xs-4">
                                        <img src="{% static 'custom/topic.jpg' %}" alt="..." class="img-thumbnail img-responsive">
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-12 col-xs-12">
                <div class="btn-group" id="bbs-side-nav">
                    <a href="" class="btn btn-default">
                        <i class="icon center-block">&#xe7e0;</i>
                        博客
                    </a>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'generic:login' %}" class="btn btn-default">
                            <i class="icon center-block">&#xe78b;</i>
                            登陆
                        </a>
                    {% else %}
                        <a href="javascript:;" class="btn btn-default" onclick="$('#writer').modal();">
                            <i class="icon center-block">&#xe7de;</i>
                            发帖
                        </a>
                    {% endif %}
                    <a href="{% url 'bbs:leader' %}" class="btn btn-default">
                        <i class="icon center-block">&#xe722;</i>
                        榜单
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block script %}
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" id="writer">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content" style="border-radius: 0;">
                <div class="modal-header">
                    <h4 class="modal-title">新帖子</h4>
                </div>
                <div class="modal-body">
                    <form method="post">{% csrf_token %}
                        <table align="center">
                            {{ newarticle.as_table }}
                            <tr>
                                <td colspan="2" id="id_contente"></td>
                            </tr>
                            <tr>
                                <td colspan="2" class="text-right">
                                    <button type="submit" class="btn btn-default">提交</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
    var E = window.wangEditor
    var editor = new E('#id_contente')
    editor.customConfig.onchange = function(html){
        $('#id_content').val(html);
    }
    editor.create()
    $('#id_content').val(editor.txt.html());
    </script>
{% endblock script %}

templates/bbs/leader.html
{% extends 'generic/base.html' %} {% load static %}
{% block content %}
    <div class="container-fluid" style="margin-top:3%;">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="hot-leader panel panel-danger">
                                <div class="panel-heading">热门榜</div>
                                <div class="panel-body">
                                    <ul class="list-unstyled">
                                        {% for row in hot_leader %}
                                        <li>
                                            {{ forloop.counter }}. <a href="{% url 'bbs:detail' row.id %}">{{ row.topic }}</a><span style="float:right">{{ row.visits }}</span>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="hot-leader panel panel-primary">
                                <div class="panel-heading">收藏榜</div>
                                <div class="panel-body">
                                    <ul class="list-unstyled">
                                        {% for row in like_leader %}
                                        <li>
                                            {{ forloop.counter }}. <a href="{% url 'bbs:detail' row.id %}">{{ row.topic }}</a><span style="float:right">{{ row.likes }}</span>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}